-- INSERT INTO MEMBER (MEMBER_ID, PASSWORD, NAME, NICKNAME, MEMBER_TYPE) VALUES ('admin', 'admin', '홍길동', '관리자 닉네임', 'ADMIN');
INSERT INTO MEMBER (MEMBER_ID, PASSWORD, NAME, NICKNAME, MEMBER_TYPE) VALUES ('admin', '$2a$10$QMCwxIeL0xACKWn6epWiJOCIa3/gMnlr4v9TpshHeB6/c7.MixLQm', '홍길동', '관리자 닉네임', 'ADMIN');


