DROP TABLE IF EXISTS MEMBER CASCADE;
DROP TABLE IF EXISTS BOARD CASCADE;
DROP TABLE IF EXISTS NEWS CASCADE;
DROP TABLE IF EXISTS TAG CASCADE ;

CREATE TABLE MEMBER (
    ID SERIAL8 NOT NULL,
    MEMBER_ID VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    NICKNAME VARCHAR(20) NOT NULL,
    MEMBER_TYPE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE BOARD (
    ID SERIAL8 NOT NULL,
    WRITER_ID int8 NOT NULL,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT NOT NULL,
    HIT int4 NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    MODIFIED_AT TIMESTAMP NOT NULL,
    BOARD_TYPE VARCHAR(20) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE NEWS (
    ID int8 NOT NULL,
    CATEGORY_NAME VARCHAR(20) NOT NULL
);

CREATE TABLE TAG (
    BOARD_ID INT8 NOT NULL,
    NAME VARCHAR(20) NOT NULL
);