database: postgresql

spring:
  datasource:
    schema: classpath*:db/${database}/schema.sql
    initialization-mode: always
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/musinsa
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    check-template-location: true
    suffix: .html
    mode: HTML5
  jwt:
    secret: musinsa_clone